#!/bin/bash

# Load environment variables from .env file
set -o allexport
source .env
set +o allexport

# Connect to DB2 database using db2 command-line tool
docker exec -it ${CONTAINER_NAME} su - db2inst1 -c "db2 connect to ${DBNAME} user db2inst1 using ${DB2INST1_PASSWORD}"

# Start interactive terminal session
docker exec -it ${CONTAINER_NAME} su - db2inst1 -c "db2"
