version: '3'
services:
  db2:
    image: ibmcom/db2:11.5.6.0
    platform: linux/amd64
    privileged: true
    container_name: ${CONTAINER_NAME}
    environment:
      - LICENSE=${LICENSE}
      - DB2INST1_PASSWORD=${DB2INST1_PASSWORD}
      - DBNAME=${DBNAME}
      - IS_OSXFS=true
      - PERSISTENT_HOME=true
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - db2data:/database
volumes:
  db2data:

