#! /bin/bash

. .config
#LOG_DIR=./logs/;
#LOG_FILE=docker_compose_logs.log

docker-compose --env-file .env up -d
echo "Saving logs to ${LOG_DIR}${DOCKER_COMPOSE_LOGS_FILE_PATH}"

docker-compose logs -t -f --no-color >> ${LOG_DIR}${DOCKER_COMPOSE_LOGS_FILE_PATH} &
