#! /bin/bash

. .config
. .env

LOG_OUTPUT_PATH="$PWD/logs/$CONTAINER_NAME/$DOCKER_COMPOSE_LOGS_FILE_NAME"

echo "LOG_OUTPUT_PATH=$LOG_OUTPUT_PATH"

docker-compose --env-file .env up -d

docker-compose logs -t -f --no-color >> ${LOG_OUTPUT_PATH} &

